services:
  image_upload_frontend:
    container_name: image_upload_frontend
    image: longa/image_upload_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - image_upload_backend
  image_upload_backend:
    container_name: image_upload_backend
    image: longa/image_upload_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=your_aws_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=aws_region
      - AWS_S3_BUCKET=s3_bucket_name_(image/file will be uploaded here)
      - BUCKET_URL=(if you have a public url for your s3 bucket)
    ports:
      - 8080:8080